name: Push to Replicate

on:
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  push_model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Cog
        uses: replicate/setup-cog@v1
        with:
          # This uses the REPLICATE_API_TOKEN secret you created
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cog push r8.im/student0129/whisperx-app-from-github
