name: Push to Replicate

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cog
        uses: replicate/actions/setup-cog@v1

      - name: Push model to Replicate
        run: cog push
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
