name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push_model:
    # This is the only line we are changing
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cog push r8.im/student0129/whisperx-app-from-github
